# Generated by Django 4.0.2 on 2022-02-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='abbreviation',
            field=models.CharField(default='dvd', max_length=200),
            preserve_default=False,
        ),
    ]
