# Generated by Django 4.0.2 on 2022-02-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_organizer', '0003_remove_movie_format_movie_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='format',
            new_name='formats',
        ),
    ]
